export interface MoUPartner {
  name: string;
  location: string;
  image?: string; // Optional logo URL
  type: string; // Type of partner (e.g., school, organization)
  date: string; // Date of MoU signing
  programs: string; // Programs offered under the MoU
  students?: number; // Optional number of students involved
}

export const moUPartners: MoUPartner[] = [
  {
    name: "SOS Hermann Gmeiner Secondary School",
    location: "Itahari",
    date: "November 24, 2024",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Shree Shanti Bhagwati Secondary School  ",
    location: "Letang-4, Morang",
    date: "May 30, 2024",
    programs: "Teleoperated Robots Workshop",
    image: "🏫",
    type: "community-based government institution",
  },

  {
    name: "Shree Janata Secondary School",
    location: "Itahari",
    date: "November 24, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Public",
  },
  {
    name: "Shree Satyanarayan Secondary School",
    location: "Biratnagar",
    date: "June 7, 2024",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Public",
  },
  {
    name: "Shree Public High School ",
    location: "Dharan",
    date: "June 14, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Eureka Residential Secondary School",
    location: "Dharan",
    date: "July 3, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "SOS Hermann Gmeiner Secondary School ",
    location: "Itahari",
    date: "November 24, 2024",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Shree Shanti Bhagwati Secondary School  ",
    location: "Letang-4, Morang",
    date: "May 30, 2024",
    programs: "Teleoperated Robots Workshop",
    image: "🏫",
    type: "community-based government institution",
  },

  {
    name: "Shree Janata Secondary School",
    location: "Itahari",
    date: "November 24, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Public",
  },
  {
    name: "Shree Satyanarayan Secondary School",
    location: "Biratnagar",
    date: "June 7, 2024",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Public",
  },
  {
    name: "Shree Public High School",
    location: "Dharan",
    date: "June 14, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Eureka Residential Secondary School",
    location: "Dharan",
    date: "July 3, 2024",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },

  {
    name: "Birendra Memorial College-CSIT",
    location: "Dharan,Sunsari",
    date: "September 22, 2024",
    programs: "Fundamentals of Robots and Robotics Workshop",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Aarambha Vidya Mandir ",
    location: "Ramdhuni,Sunsari",
    date: "2024",
    programs: "Young Robotics Scientist Program 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Sayapatri Shishu Sadan English School ",
    location: "Itahari,Sunsari",
    date: "December 13, 2024",
    programs: "Young Robotics Scientist Program 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Prakashpur Yuwa Jamat ",
    location: "Barahakshetra,Sunsari",
    date: " 2024",
    programs: "Fundamental of robots and robotics",
    image: "🏫",
    type: "Private",
  },

  {
    name: "𝚁𝙰𝙹𝙰𝙱𝙰𝚂 𝚂𝙴𝙲𝙾𝙽𝙳𝙰𝚁𝚈 𝚂𝙲𝙷𝙾𝙾𝙻  ",
    location: "Barahakshetra, Sunsari",
    date: "March 21, 2025",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Nawa Kiran English Secondary school",
    location: "Itahari,Sunsari",
    date: "December 13, 2024",
    programs: "Young Robotics Scientist Program 2081",
    image: "🏫",
    type: "Private",
  },

  {
    name: "Summit Secondary Boarding School ",
    location: "Dharan-9, Sunsari",
    date: "March 25, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: " Letang Residential Secondary School",
    location: "Letang,Morang",
    date: "April 24, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },

  {
    name: "Nobel Education  and Development foundation ",
    location: "Letang,Morang",
    date: "April 24, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },

  {
    name: "Letang GREEN Valley Academy  ",
    location: "Letang,Morang",
    date: "April 29, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Little Flowers' Boarding School ",
    location: "Letang,Morang",
    date: "April 29, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: " Siddhartha Memorial English School ",
    location: "Barahakshetra,Kalabanjar, Sunsari",
    date: "March 21, 2025",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "  Bharoul Bal Mandir Secondary English School",
    location: "Barahakshetra, Sunsari",
    date: "May 2, 2025",
    programs: "Robotics Camp 2081",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Morang Pathibhara English School",
    location: "Budhabare, Letang-2, Morang",
    date: "May 5, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
  {
    name: "Galaxy Academy ",
    location: "Letang, Morang ",
    date: "May 19, 2025",
    programs: "Young Robotics Scientist Program",
    image: "🏫",
    type: "Private",
  },
];
